use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Creates a minimal `home.nix` in `dir` if one doesn't already exist,
/// importing `nixbox-packages.nix` alongside it.
pub fn ensure_home_nix(dir: &Path) -> Result<()> {
    let home_nix = dir.join("home.nix");
    if home_nix.exists() {
        return Ok(());
    }
    fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    let username = std::env::var("USER").unwrap_or_else(|_| "user".into());
    let home_dir = std::env::var("HOME").unwrap_or_else(|_| format!("/home/{username}"));
    let content = format!(
        "# Generated by nixbox. Feel free to extend this file.\n\
         {{ config, pkgs, ... }}:\n\
         {{\n\
         \x20 imports = [ ./nixbox-home-packages.nix ];\n\n\
         \x20 home.username = \"{username}\";\n\
         \x20 home.homeDirectory = \"{home_dir}\";\n\n\
         \x20 # Keep this in sync with your nixpkgs channel.\n\
         \x20 home.stateVersion = \"24.11\";\n\
         \x20 programs.home-manager.enable = true;\n\
         }}\n"
    );
    fs::write(&home_nix, content).with_context(|| format!("writing {}", home_nix.display()))?;
    Ok(())
}

const MANIFEST_HEADER: &str = "# Managed by nixbox. Do not edit by hand.";

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Manifest {
    pub packages: BTreeSet<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FlakeManifest {
    pub modules: BTreeMap<String, String>,
    pub packages: BTreeMap<String, String>,
}

impl FlakeManifest {
    pub fn add(&mut self, input: String, module: String) -> bool {
        self.modules.insert(input, module).is_none()
    }

    pub fn add_package(&mut self, input: String, package: String) -> bool {
        self.packages.insert(input, package).is_none()
    }
}

impl Manifest {
    pub fn add(&mut self, pname: &str) -> bool {
        self.packages.insert(pname.to_string())
    }

    pub fn remove(&mut self, pname: &str) -> bool {
        self.packages.remove(pname)
    }
}

pub struct ManagedFile {
    path: PathBuf,
}

impl ManagedFile {
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { path: path.into() }
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn load(&self) -> Result<Manifest> {
        if !self.path.exists() {
            return Ok(Manifest::default());
        }
        let raw = fs::read_to_string(&self.path)
            .with_context(|| format!("reading {}", self.path.display()))?;
        Ok(parse(&raw))
    }

    pub fn write_home_manager(&self, manifest: &Manifest) -> Result<()> {
        self.write(render_home_manager(manifest))
    }

    pub fn write_nixos(&self, manifest: &Manifest) -> Result<()> {
        self.write(render_nixos(manifest))
    }

    fn write(&self, content: String) -> Result<()> {
        if let Some(parent) = self.path.parent() {
            fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
        }
        fs::write(&self.path, content).with_context(|| format!("writing {}", self.path.display()))
    }
}

pub struct ManagedFlakeFile {
    path: PathBuf,
}

impl ManagedFlakeFile {
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { path: path.into() }
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn load(&self) -> Result<FlakeManifest> {
        if !self.path.exists() {
            return Ok(FlakeManifest::default());
        }
        let raw = fs::read_to_string(&self.path)
            .with_context(|| format!("reading {}", self.path.display()))?;
        let mut manifest = FlakeManifest::default();
        let mut in_module_block = false;
        let mut in_package_block = false;
        for line in raw.lines() {
            let line = line.trim();
            if line == "# nixbox:flakes:start" {
                in_module_block = true;
                continue;
            }
            if line == "# nixbox:flakes:end" {
                in_module_block = false;
                continue;
            }
            if line == "# nixbox:flake-packages:start" {
                in_package_block = true;
                continue;
            }
            if line == "# nixbox:flake-packages:end" {
                in_package_block = false;
                continue;
            }
            let Some(path) = line.strip_prefix("inputs.\"") else {
                continue;
            };
            let Some((input, output)) = path.split_once("\".") else {
                continue;
            };
            if in_module_block {
                manifest
                    .modules
                    .insert(input.to_string(), output.to_string());
            } else if in_package_block
                && let Some(package) = output
                    .strip_prefix("packages.${pkgs.system}.\"")
                    .and_then(|value| value.strip_suffix('"'))
            {
                manifest
                    .packages
                    .insert(input.to_string(), package.to_string());
            }
        }
        Ok(manifest)
    }

    pub fn write_home_manager(&self, manifest: &FlakeManifest) -> Result<()> {
        self.write(manifest, "home.packages")
    }

    pub fn write_nixos(&self, manifest: &FlakeManifest) -> Result<()> {
        self.write(manifest, "environment.systemPackages")
    }

    fn write(&self, manifest: &FlakeManifest, package_option: &str) -> Result<()> {
        if let Some(parent) = self.path.parent() {
            fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
        }
        let mut imports = String::new();
        imports.push_str("\t\t# nixbox:flakes:start\n");
        for (input, module) in &manifest.modules {
            imports.push_str(&format!("\t\tinputs.\"{input}\".{module}\n"));
        }
        imports.push_str("\t\t# nixbox:flakes:end\n");
        let mut packages = String::new();
        packages.push_str("\t\t# nixbox:flake-packages:start\n");
        for (input, package) in &manifest.packages {
            packages.push_str(&format!(
                "\t\tinputs.\"{input}\".packages.${{pkgs.system}}.\"{}\"\n",
                escape_nix_string(package)
            ));
        }
        packages.push_str("\t\t# nixbox:flake-packages:end\n");
        let content = format!(
            "# Managed by nixbox. Do not edit by hand.\n{{ inputs, pkgs, ... }}:\n{{\n\timports = [\n{imports}\t];\n\t{package_option} = [\n{packages}\t];\n}}\n"
        );
        fs::write(&self.path, content).with_context(|| format!("writing {}", self.path.display()))
    }
}

fn escape_nix_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn parse(raw: &str) -> Manifest {
    let mut packages = BTreeSet::new();
    let mut in_block = false;
    for line in raw.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("# nixbox:packages:start") {
            in_block = true;
            continue;
        }
        if trimmed.starts_with("# nixbox:packages:end") {
            in_block = false;
            continue;
        }
        if in_block && !trimmed.is_empty() && !trimmed.starts_with('#') {
            let token = trimmed.trim_end_matches(';');
            if let Some(pname) = token.strip_prefix("pkgs.") {
                packages.insert(pname.to_string());
            }
        }
    }
    Manifest { packages }
}

fn render_packages(manifest: &Manifest) -> String {
    let mut out = String::new();
    out.push_str("    # nixbox:packages:start\n");
    for pname in &manifest.packages {
        out.push_str(&format!("    pkgs.{}\n", pname));
    }
    out.push_str("    # nixbox:packages:end\n");
    out
}

fn render_home_manager(manifest: &Manifest) -> String {
    format!(
        "{header}\n{{ pkgs, ... }}:\n{{\n  home.packages = [\n{body}  ];\n}}\n",
        header = MANIFEST_HEADER,
        body = render_packages(manifest),
    )
}

fn render_nixos(manifest: &Manifest) -> String {
    format!(
        "{header}\n{{ pkgs, ... }}:\n{{\n  environment.systemPackages = [\n{body}  ];\n}}\n",
        header = MANIFEST_HEADER,
        body = render_packages(manifest),
    )
}

/// Status of an `ensure_imported` call.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImportStatus {
    /// The managed file was already imported by the main file.
    AlreadyImported,
    /// The managed file was inserted into an existing `imports = [ ... ]` list.
    InsertedIntoList,
    /// No `imports` list was present; a new one was prepended.
    CreatedList,
    /// The main file does not exist on disk — nothing was modified.
    MainFileMissing,
}

/// Ensures `managed_file` is imported by `main_file`. Inserts the import
/// idempotently. Returns a status describing what (if anything) was done.
pub fn ensure_imported(main_file: &Path, managed_file: &Path) -> Result<ImportStatus> {
    if !main_file.exists() {
        return Ok(ImportStatus::MainFileMissing);
    }
    let main_dir = main_file
        .parent()
        .with_context(|| format!("{} has no parent", main_file.display()))?;
    let rel = pathdiff_relative(managed_file, main_dir);
    let import_str = if rel.starts_with("./") || rel.starts_with("../") || rel.starts_with('/') {
        rel
    } else {
        format!("./{}", rel)
    };

    let raw = fs::read_to_string(main_file)
        .with_context(|| format!("reading {}", main_file.display()))?;

    if contains_import(&raw, &import_str) {
        return Ok(ImportStatus::AlreadyImported);
    }

    let (new_content, status) = if let Some(updated) = insert_into_imports_list(&raw, &import_str) {
        (updated, ImportStatus::InsertedIntoList)
    } else {
        let updated = create_imports_list(&raw, &import_str)
            .with_context(|| format!("could not locate body attrset in {}", main_file.display()))?;
        (updated, ImportStatus::CreatedList)
    };

    fs::write(main_file, new_content)
        .with_context(|| format!("writing {}", main_file.display()))?;
    Ok(status)
}

/// Best-effort relative path from `base` to `target`. Falls back to the
/// absolute target when no relative path is possible.
fn pathdiff_relative(target: &Path, base: &Path) -> String {
    let target = target
        .canonicalize()
        .unwrap_or_else(|_| target.to_path_buf());
    let base = base.canonicalize().unwrap_or_else(|_| base.to_path_buf());
    let target_components: Vec<_> = target.components().collect();
    let base_components: Vec<_> = base.components().collect();
    let mut common = 0;
    while common < target_components.len()
        && common < base_components.len()
        && target_components[common] == base_components[common]
    {
        common += 1;
    }
    let ups = base_components.len() - common;
    if ups == 0 && common == target_components.len() {
        return target.to_string_lossy().into_owned();
    }
    let mut parts: Vec<String> = std::iter::repeat_n("..".to_string(), ups).collect();
    for c in &target_components[common..] {
        parts.push(c.as_os_str().to_string_lossy().into_owned());
    }
    parts.join("/")
}

fn contains_import(raw: &str, import_str: &str) -> bool {
    // Match the import path as a whole token to avoid prefix collisions
    // (e.g. `./nixbox-home-packages.nix` vs `./nixbox-home-packages.nix.bak`).
    for (idx, _) in raw.match_indices(import_str) {
        let after = raw[idx + import_str.len()..].chars().next();
        let token_continues =
            matches!(after, Some(c) if c.is_alphanumeric() || c == '-' || c == '_' || c == '.');
        if !token_continues {
            return true;
        }
    }
    false
}

/// Try to insert `import_str` into an existing `imports = [ ... ]` list.
/// Returns the updated content, or None when no imports list is found.
fn insert_into_imports_list(raw: &str, import_str: &str) -> Option<String> {
    let imports_pos = find_imports_keyword(raw)?;
    let bracket_rel = raw[imports_pos..].find('[')?;
    let bracket_pos = imports_pos + bracket_rel;
    let after_bracket = bracket_pos + 1;
    let rest = &raw[after_bracket..];

    // Detect multi-line vs single-line list.
    let multiline = rest
        .chars()
        .take_while(|c| c.is_whitespace() && *c != '\n')
        .count()
        < rest.len()
        && rest
            .chars()
            .take_while(|c| c.is_whitespace())
            .any(|c| c == '\n');

    let mut out = String::with_capacity(raw.len() + import_str.len() + 8);
    out.push_str(&raw[..after_bracket]);
    if multiline {
        // Find the indentation used by existing entries; fall back to 4 spaces.
        let indent = detect_list_indent(rest).unwrap_or_else(|| "    ".to_string());
        out.push('\n');
        out.push_str(&indent);
        out.push_str(import_str);
        out.push_str(&raw[after_bracket..]);
    } else {
        out.push(' ');
        out.push_str(import_str);
        // If the original char right after `[` isn't whitespace or `]`, add a space.
        if let Some(next) = rest.chars().next()
            && !next.is_whitespace()
            && next != ']'
        {
            out.push(' ');
        }
        out.push_str(&raw[after_bracket..]);
    }
    Some(out)
}

fn detect_list_indent(after_bracket: &str) -> Option<String> {
    for line in after_bracket.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let indent: String = line.chars().take_while(|c| c.is_whitespace()).collect();
        if !indent.is_empty() {
            return Some(indent);
        }
        return None;
    }
    None
}

/// Locate the `imports` identifier as a key in an attrset (not inside a string
/// or comment). Naive scan that skips line comments and string literals.
fn find_imports_keyword(raw: &str) -> Option<usize> {
    let bytes = raw.as_bytes();
    let mut i = 0;
    let mut in_string = false;
    let mut in_line_comment = false;
    while i < bytes.len() {
        let b = bytes[i];
        if in_line_comment {
            if b == b'\n' {
                in_line_comment = false;
            }
            i += 1;
            continue;
        }
        if in_string {
            if b == b'\\' && i + 1 < bytes.len() {
                i += 2;
                continue;
            }
            if b == b'"' {
                in_string = false;
            }
            i += 1;
            continue;
        }
        if b == b'#' {
            in_line_comment = true;
            i += 1;
            continue;
        }
        if b == b'"' {
            in_string = true;
            i += 1;
            continue;
        }
        if b == b'i' && raw[i..].starts_with("imports") {
            let prev_ok = i == 0
                || !matches!(
                    bytes[i - 1],
                    b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'_' | b'-'
                );
            let after = i + "imports".len();
            let next_ok = after >= bytes.len()
                || !matches!(
                    bytes[after],
                    b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'_' | b'-'
                );
            if prev_ok && next_ok {
                return Some(i);
            }
        }
        i += 1;
    }
    None
}

/// Insert a new `imports = [ <path> ];` line at the top of the outer attrset
/// body. The outer body is identified as the first `{` that appears on its
/// own after the function-argument header (`{ ... }:`).
fn create_imports_list(raw: &str, import_str: &str) -> Option<String> {
    // Find a `{` that begins the body. Heuristic: the first `{` that comes
    // after a `:` outside of strings/comments. This skips the args attrset.
    let bytes = raw.as_bytes();
    let mut i = 0;
    let mut in_string = false;
    let mut in_line_comment = false;
    let mut seen_colon = false;
    let mut depth: i32 = 0;
    while i < bytes.len() {
        let b = bytes[i];
        if in_line_comment {
            if b == b'\n' {
                in_line_comment = false;
            }
            i += 1;
            continue;
        }
        if in_string {
            if b == b'\\' && i + 1 < bytes.len() {
                i += 2;
                continue;
            }
            if b == b'"' {
                in_string = false;
            }
            i += 1;
            continue;
        }
        match b {
            b'#' => in_line_comment = true,
            b'"' => in_string = true,
            b'{' => {
                if seen_colon && depth == 0 {
                    let mut out = String::with_capacity(raw.len() + import_str.len() + 16);
                    out.push_str(&raw[..=i]);
                    out.push_str(&format!("\n  imports = [ {} ];\n", import_str));
                    out.push_str(&raw[i + 1..]);
                    return Some(out);
                }
                depth += 1;
            }
            b'}' => depth -= 1,
            b':' if depth == 0 => seen_colon = true,
            _ => {}
        }
        i += 1;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_home_manager() {
        let mut m = Manifest::default();
        m.add("ripgrep");
        m.add("fd");
        let rendered = render_home_manager(&m);
        let parsed = parse(&rendered);
        assert_eq!(parsed.packages, m.packages);
    }

    #[test]
    fn round_trip_nixos() {
        let mut m = Manifest::default();
        m.add("htop");
        let rendered = render_nixos(&m);
        let parsed = parse(&rendered);
        assert_eq!(parsed.packages, m.packages);
    }

    #[test]
    fn inserts_into_multiline_imports() {
        let raw =
            "{ pkgs, ... }:\n{\n    imports = [\n        ./a.nix\n        ./b.nix\n    ];\n}\n";
        let out = insert_into_imports_list(raw, "./nixbox-home-packages.nix").unwrap();
        assert!(out.contains("./nixbox-home-packages.nix\n        ./a.nix"));
    }

    #[test]
    fn inserts_into_singleline_imports() {
        let raw = "{ pkgs, ... }:\n{ imports = [ ./a.nix ]; }\n";
        let out = insert_into_imports_list(raw, "./mgr.nix").unwrap();
        assert!(out.contains("imports = [ ./mgr.nix ./a.nix ];"));
    }

    #[test]
    fn inserts_into_empty_imports() {
        let raw = "{ pkgs, ... }:\n{ imports = []; }\n";
        let out = insert_into_imports_list(raw, "./mgr.nix").unwrap();
        assert!(out.contains("imports = [ ./mgr.nix];"));
    }

    #[test]
    fn detects_existing_import_idempotent() {
        let raw = "{ pkgs, ... }:\n{ imports = [ ./nixbox-home-packages.nix ]; }\n";
        assert!(contains_import(raw, "./nixbox-home-packages.nix"));
    }

    #[test]
    fn does_not_match_substring_prefix() {
        let raw = "{ pkgs, ... }:\n{ imports = [ ./nixbox-home-packages.nix.bak ]; }\n";
        assert!(!contains_import(raw, "./nixbox-home-packages.nix"));
    }

    #[test]
    fn creates_imports_list_when_missing() {
        let raw = "{ pkgs, ... }:\n{\n  home.packages = [ pkgs.htop ];\n}\n";
        let out = create_imports_list(raw, "./mgr.nix").unwrap();
        assert!(out.contains("imports = [ ./mgr.nix ];"));
        // Ensure original content still present.
        assert!(out.contains("home.packages"));
    }

    #[test]
    fn ignores_imports_word_inside_string() {
        let raw = "{ pkgs, ... }:\n{ x = \"imports\"; imports = [ ./a.nix ]; }\n";
        let pos = find_imports_keyword(raw).unwrap();
        // Should find the second occurrence (the real key), not the one in the string.
        assert!(raw[pos..].starts_with("imports = ["));
    }

    #[test]
    fn flake_manifest_round_trips_module_imports() {
        let path = std::env::temp_dir().join(format!("nixbox-flakes-{}.nix", std::process::id()));
        let _ = fs::remove_file(&path);
        let managed = ManagedFlakeFile::new(&path);
        let mut manifest = FlakeManifest::default();
        manifest.add("owner/module".into(), "homeManagerModules.default".into());
        manifest.add_package("owner/package".into(), "default".into());

        managed.write_home_manager(&manifest).unwrap();

        let loaded = managed.load().unwrap();
        assert_eq!(loaded.modules, manifest.modules);
        assert_eq!(loaded.packages, manifest.packages);
        let rendered = fs::read_to_string(&path).unwrap();
        assert!(rendered.contains("inputs.\"owner/package\".packages.${pkgs.system}.\"default\""));
        assert!(rendered.contains("home.packages = ["));
        let _ = fs::remove_file(path);
    }

    #[test]
    fn flake_manifest_renders_nixos_packages() {
        let path =
            std::env::temp_dir().join(format!("nixbox-system-flakes-{}.nix", std::process::id()));
        let _ = fs::remove_file(&path);
        let managed = ManagedFlakeFile::new(&path);
        let mut manifest = FlakeManifest::default();
        manifest.add_package("owner/package".into(), "bun-latest".into());

        managed.write_nixos(&manifest).unwrap();

        let rendered = fs::read_to_string(&path).unwrap();
        assert!(rendered.contains("environment.systemPackages = ["));
        assert!(
            rendered.contains("inputs.\"owner/package\".packages.${pkgs.system}.\"bun-latest\"")
        );
        let _ = fs::remove_file(path);
    }
}
